version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
