version: '2'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      REDIS_URL: redis://redis:6379
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./index.js:/root/index.js:ro
      - ./package.json:/root/package.json:ro
      - ./.babelrc:/root/.babelrc:ro
      - ./server:/root/server:ro
      - ./src:/root/src:ro
      - ./public:/root/public
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
