version: '2'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    volumes:
      - ./index.js:/root/index.js:ro
      - ./package.json:/root/package.json:ro
      - ./server:/root/server:ro
      - ./src:/root/src:ro
      - ./public:/root/public
