version: '3'
services:
  web:
    image: node:9.5
    working_dir: /app
    command: bash -c "npm install && npm run build && tail -f /dev/null"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.babelrc:/app/.babelrc:ro
      - ./server:/app/server:ro
      - ./src:/app/src:ro
      - ./public:/app/public
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
